### ISSUE TITLE
Clipboard cut demo works but copy fails and reports success

### ISSUE THREAD

**Issue by 1j01** [NOtherDev/whatwebcando#45]
On https://whatwebcando.today/clipboard.html,
the "Copy email address programatically" button doesn't work

```
15:28:34 User performed cut operation. Payload is: .

15:28:34 Cutting text command was successful.

15:28:35 User performed paste operation. Payload is: Hello! Cut me programatically or maybe try pasting here..

15:28:37 User performed copy operation. Payload is: .

15:28:37 Copy email command was successful.

15:28:38 User performed paste operation. Payload is: Hello! Cut me programatically or maybe try pasting here..


```

**Comment by 1j01** [comment]
The document selection range setting isn't working (whereas textarea.select() works).

**Comment by NOtherDev** [comment]
In which browser are you checking? I've verified in Chrome on desktop and on mobile and it works fine.
There was an inconsistency when you had something already selected – this should be fixed now.

**Comment by 1j01** [comment]
It still doesn't work for me, Chrome 65.0.3325.88 on Windows 10

**Comment by NOtherDev** [comment]
Yeah, definitely, because apparently I badly broke it yesterday :wink:
Can you check it once again?

**Comment by 1j01** [comment]
Works now! 👍
